### DISCUSSION TITLE
Metarank failed to parse arg data. How to resolve this?

### DISCUSSION THREAD

**Discussion by quachhengtony** [metarank/metarank#1051] [Q&A]
I'm following the tutorial on how to get started with Metarank. I cannot start Metarank with Docker compose. Does any one know how to fix this? Thank you.

I'm on:
- Windows 11
- Docker with WSL2 

My docker compose:
```
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  metarank:
    container_name: metarank
    image: metarank/metarank:latest
    depends_on:
      - redis
    command: "standalone -c config.yml -d events.jsonl.gz"
    volumes:
      - ./metarank:/opt/metarank
    ports:
      - "8080:8080"
      - "6123:6123"
```

Docker logs:
![image](https://github.com/metarank/metarank/assets/29624687/b96e741a-67dd-4718-9e3a-6facbef680d9)

My file structure:
![image](https://github.com/metarank/metarank/assets/29624687/092e5354-722b-4ac9-8532-7d049d6444df)
