### DISCUSSION TITLE
Format of ttl value

### DISCUSSION THREAD

**Discussion by Currie32** [metarank/metarank#1321] [General]
Hey there,

For the [ttl value when using Redis for training](https://github.com/metarank/metarank/blob/master/doc/configuration/overview.md?plain=1#L85), how should it be formatted?:
- `ttl: 7d`
- `ttl: "7d"`
- `ttl: 7.days`
- `ttl: "7.days"`
- `ttl: 7 days`
- `ttl: "7 days"`

Thanks for the help!

**Comment by shuttie** [comment]
The format is `<number><prefix>`, where prefix is one of `[d, h, m, s]`. Example: `7d`, `24h`

**Comment by Currie32** [comment]
Thanks, and just to confirm its location, it should go in the config file, under `train`, e.g.:
```
state:
  type: redis
  host: example.host.com
  port: 1234

train:
  type: redis
  host: example.host.com
  port: 1234
  ttl: 7d

features:
...

models:
...
```
