### ISSUE TITLE
Feature storage is not optimal for shared fields

### ISSUE THREAD

**Issue by ohuarte-matrix** [metarank/metarank#1145]
When you configure for example two features using the same text field:

 ```
 - type: field_match
    name: query_title_bm25
    itemField: item.title
    rankingField: ranking.query
    method:
      type: bm25
      language: english
      termFreq: /data/term-freq.json

  - name: title_match
    type: field_match
    itemField: item.title
    rankingField: ranking.query
    method:
      type: term
      language: en
```

The content of this event text field is stored twice, one by each feature

I think it should be better if metarank try to reuse this content once with the different features.

Right now the current approach can make grow the space dedicated to feature storage.

Many thanks for your great work
