### ISSUE TITLE
Memory leak when using Redis persistence

### ISSUE THREAD

**Issue by colin-ly** [metarank/metarank#1257]
Hello, 

I have encountered an issue seem to be a memory leak when running the metarank demo in the [quickstart guide](https://docs.metarank.ai/introduction/quickstart).

At first, I ran metarank with the default config, standalone mode with local persistence. I also ran performance test with postman (40 virtual users) and monitor the memory usage in the EC2 instance. The memory usage of java was stable during the test, with 1.3GB

```
top - 01:41:04 up 10:19,  3 users,  load average: 0.31, 0.48, 0.27
Tasks: 128 total,   1 running, 127 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.6 us,  2.9 sy,  0.0 ni, 70.5 id,  0.0 wa,  0.0 hi,  0.5 si, 13.5 st
MiB Mem :   3827.8 total,   1373.0 free,   1740.9 used,    713.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1871.9 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  19058 root      20   0 3773780   1.3g  36364 S  23.0  35.6   3:32.36 java
  19036 root      20   0 1491908  18036  13532 S   2.3   0.5   0:04.40 containerd-shim
  18779 root      20   0 1643212  76652  50900 S   2.0   2.0   0:04.05 dockerd
```

Then, I also ran metarank with Redis persistence (aws ElastiCache) by adding the following configuration to the default configuration. 
```
state:
  type: redis
  host: colintest.vhrll9.ng.0001.usw2.cache.amazonaws.com
  port: 6379
  format: binary

  cache:
    maxSize: 1024
    ttl: 1h
    clientTracking: true

  pipeline:
    maxSize: 128
    flushPeriod: 1s 
    enabled: true

  timeout:
    connect: 1s
    socket: 1s
    command: 1s

  db:
    state: 0
    values: 1
    rankings: 2
    models: 3
```
At first, the java service utilized around 600MB, after 16000 requests, the memory usage reached 3.2GB. It crashed after reaching the memory limit of the instance. However, there was no error message in the logs.  

```
top - 02:13:02 up 10:51,  3 users,  load average: 0.05, 0.32, 0.27
Tasks: 129 total,   1 running, 128 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.5 sy,  0.0 ni, 98.8 id,  0.0 wa,  0.0 hi,  0.2 si,  0.3 st
MiB Mem :   3827.8 total,   2094.9 free,    954.5 used,    778.4 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2658.3 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  20065 root      20   0 3834236 586884  37276 S   0.3  15.0   3:28.56 java
      1 root      20   0  170824  16600  10100 S   0.0   0.4   0:03.57 systemd
``` 
```
top - 02:27:25 up 11:05,  3 users,  load average: 1.16, 1.06, 0.65
Tasks: 128 total,   2 running, 126 sleeping,   0 stopped,   0 zombie
%Cpu(s): 27.2 us,  3.6 sy,  0.0 ni, 54.2 id,  1.3 wa,  0.0 hi,  2.9 si, 10.7 st
MiB Mem :   3827.8 total,    106.2 free,   3659.3 used,     62.3 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.     19.9 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  20065 root      20   0 6529536   3.2g   7260 S  57.3  85.6   9:13.00 java
  20043 root      20   0 1491908   6272   1624 S   2.3   0.2   0:12.09 containerd-shim
  18779 root      20   0 1643212  27656   1692 S   2.0   0.7   0:18.96 dockerd
     51 root      20   0       0      0      0 S   0.7   0.0   0:00.36 kswapd0
```
It seems to be a memory leak issue happened when Redis persistence is used. I also tried to change Redis cache and pipeline config, but nothing worked.
