### ISSUE TITLE
cryptic error message on incorrect feature definition

### ISSUE THREAD

**Issue by shuttie** [metarank/metarank#482]
```
DecodingFailure(Attempt to decode value on failed cursor, List(DownField(values), DownArray, DownField(features)))
```

On a config:
```
bootstrap:
  source:
    type: file
    path: /data
  workdir: /data

inference:
  port: 8080
  host: "0.0.0.0"
  source:
    type: rest
  state:
    type: redis
    host: localhost:6379
    format: json

models:
  xgboost:
    type: lambdamart
    path: /data/xgboost.model
    backend:
      type: xgboost
    weights:
      click: 1
    features:
      - type
features:
- name: type
  type: string
  scope: item
  source: item.type
```

It should be more human friendly.
