### ISSUE TITLE
Event folder is not properly read in docker-compose

### ISSUE THREAD

**Issue by vgoloviznin** [metarank/metarank#627]
When events are specified in a folder, they are not properly read by Metarank which results in a weird error. If a file is provided directly, events import is working as expected.

```shell
metarank_standalone  | 16:46:08.562 INFO  ai.metarank.main.command.Train$ - training model for train=0 test=0
metarank_standalone  | [16:46:08] WARNING: /workspace/src/learner.cc:1350: Empty dataset at worker: 0
metarank_standalone  | [16:46:08] WARNING: /workspace/src/learner.cc:1350: Empty dataset at worker: 0
metarank_standalone  | [16:46:08] WARNING: /workspace/src/learner.cc:1350: Empty dataset at worker: 0
metarank_standalone  | [16:46:08] WARNING: /workspace/src/learner.cc:1350: Empty dataset at worker: 0
metarank_standalone  | java.lang.NumberFormatException: For input string: "-nan"
metarank_standalone  | 	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
metarank_standalone  | 	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
metarank_standalone  | 	at java.base/java.lang.Double.parseDouble(Double.java:543)
metarank_standalone  | 	at scala.collection.StringOps$.toDouble$extension(StringOps.scala:956)
metarank_standalone  | 	at io.github.metarank.ltrlib.booster.XGBoostBooster.evalMetric(XGBoostBooster.scala:17)
metarank_standalone  | 	at io.github.metarank.ltrlib.booster.XGBoostBooster.evalMetric(XGBoostBooster.scala:11)
metarank_standalone  | 	at io.github.metarank.ltrlib.ranking.pairwise.LambdaMART.$anonfun$fit$7(LambdaMART.scala:67)
metarank_standalone  | 	at io.github.metarank.ltrlib.ranking.pairwise.LambdaMART.$anonfun$fit$7$adapted(LambdaMART.scala:62)
metarank_standalone  | 	at scala.collection.immutable.Range.map(Range.scala:59)
metarank_standalone  | 	at io.github.metarank.ltrlib.ranking.pairwise.LambdaMART.fit(LambdaMART.scala:62)
metarank_standalone  | 	at ai.metarank.rank.LambdaMARTModel.train(LambdaMARTModel.scala:38)
metarank_standalone  | 	at ai.metarank.main.command.Train$.$anonfun$train$16(Train.scala:54)
metarank_standalone  | 	at apply @ ai.metarank.main.command.Train$.$anonfun$train$15(Train.scala:54)
metarank_standalone  | 	at flatMap @ ai.metarank.main.command.Train$.$anonfun$train$15(Train.scala:54)
metarank_standalone  | 	at apply @ ai.metarank.util.Logging.info(Logging.scala:10)
metarank_standalone  | 	at flatMap @ ai.metarank.main.command.Train$.$anonfun$train$14(Train.scala:53)
metarank_standalone  | 	at apply @ ai.metarank.main.command.Train$.$anonfun$train$11(Train.scala:51)
metarank_standalone  | 	at map @ ai.metarank.main.command.Train$.$anonfun$train$11(Train.scala:51)
metarank_standalone  | 	at flatMap @ ai.metarank.main.command.Train$.$anonfun$train$11(Train.scala:51)
metarank_standalone  | 	at apply @ ai.metarank.main.command.Train$.$anonfun$train$7(Train.scala:49)
metarank_standalone  | 	at flatMap @ ai.metarank.main.command.Train$.$anonfun$train$7(Train.scala:46)
metarank_standalone  | 	at apply @ ai.metarank.util.Logging.info(Logging.scala:10)
metarank_standalone  | 	at flatMap @ ai.metarank.main.command.Train$.$anonfun$train$6(Train.scala:45)
metarank_standalone  | 	at apply @ ai.metarank.main.command.Train$.$anonfun$train$3(Train.scala:44)
metarank_standalone  | 	at flatMap @ ai.metarank.main.command.Train$.$anonfun$train$3(Train.scala:44)
metarank_standalone  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
metarank_standalone  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
metarank_standalone  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
metarank_standalone exited with code 1
```

Docker compose configuration:
```yaml
version: "3"

services:
  redis:
    container_name: redis
    image: "redis:7.0.0"
    ports:
      - "6379:6379"

  metarank_standalone:
    container_name: metarank_standalone
    image: metarank/metarank:0.5.3
    depends_on:
      - redis
    command: "standalone --config /data/config.yml --data /data/events"
    volumes:
      - ./metarank:/data
    ports:
      - "8080:8080"
      - "6123:6123"
      - "8081:8081"
```
