### ISSUE TITLE
Facing Issue while running the metarank [DecodingFailure]

### ISSUE THREAD

**Issue by ravichoudhary33** [metarank/metarank#644]
`docker run -i -t -p 8080:8080 -v $(pwd):/opt/metarank metarank/metarank:0.5.4 standalone --config /opt/metarank/config.yml --data /opt/metarank/events.jsonl.gz`

output
```
+ exec /opt/java/openjdk/bin/java -jar /app/metarank.jar standalone --config /opt/metarank/config.yml --data /opt/metarank/events.jsonl.gz
12:29:23.274 INFO  ai.metarank.main.Main$ - Metarank v0.5.4 is starting.
DecodingFailure(cannot parse a feature definition of type 'rate', List(DownField(scope), MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, DownArray, DeleteGoParent, DownArray, DownField(features)))
```

**Comment by vgoloviznin** [comment]
Hey @ravichoudhary33, can you post the `features` section of your configuration file?

**Comment by ravichoudhary33** [comment]
@vgoloviznin 
here is the `features` section of the config file

```
features:
  - name: popularity
    type: number
    scope: item
    source: metadata.popularity

  - name: vote_avg
    type: number
    scope: item
    source: metadata.vote_avg

  - name: vote_cnt
    type: number
    scope: item
    source: metadata.vote_cnt

  - name: budget
    type: number
    scope: item
    source: metadata.budget

  - name: release_date
    type: number
    scope: item
    source: metadata.release_date

  - name: runtime
    type: number
    scope: item
    source: metadata.runtime

  - name: title_length
    type: word_count
    source: metadata.title
    scope: item

  - name: genre
    type: string
    scope: item
    source: metadata.genres
    encode: onehot
    values:
      - drama
      - comedy
      - thriller
      - action
      - adventure
      - romance
      - crime
      - science fiction
      - fantasy
      - family
      - horror
      - mystery
      - animation
      - history
      - music

  - name: ctr
    type: rate
    top: click
    bottom: impression
    bucket: 24h
    periods: [7,30]
    normalize:
      weight: 10

  - name: liked_genre
    type: interacted_with
    interaction: click
    field: metadata.genres
    scope: session
    count: 100
    duration: 24h

  - name: liked_actors
    type: interacted_with
    interaction: click
    field: metadata.actors
    scope: session
    count: 100
    duration: 24h

  - name: liked_tags
    type: interacted_with
    interaction: click
    field: metadata.tags
    scope: session
    count: 100
    duration: 24h

  - name: liked_director
    type: interacted_with
    interaction: click
    field: metadata.director
    scope: session
    count: 100
    duration: 24h

  - name: visitor_click_count
    type: interaction_count
    interaction: click
    scope: session

  - name: global_item_click_count
    type: interaction_count
    interaction: click
    scope: item

  - name: day_item_click_count
    type: window_count
    interaction: click
    scope: item
    bucket: 24h
    periods: [7,30]
```

**Comment by ravichoudhary33** [comment]
here i can see `ctr` feature have type `rate`
```
- name: ctr
    type: rate
    top: click
    bottom: impression
    bucket: 24h
    periods: [7,30]
    normalize:
      weight: 10
```
