### ISSUE TITLE
Custom session finalization

### ISSUE THREAD

**Issue by shuttie** [metarank/metarank#902]
Metarank now supports only time-based session finalization: after 30 mins of inactivity session is considered closed and flushed to the persistent store. It would be nice to support other options, for example:
* sending a custom interaction type (like `type=session-close`)

This may also require a small refactoring of the session config from:
```
core:
  clickthrough:
    maxSessionLength: 60s
```

to something like:
```
core:
   clickthrough:
    policy: time
    maxSessionLength: 60s
```
and:
```
core:
   clickthrough:
    policy: interaction
    type: session-finish
```
