### ISSUE TITLE
Can't start Metarank recommendations with empty feature list

### ISSUE THREAD

**Issue by vgoloviznin** [metarank/metarank#957]
Given the following YAML configuration, Metarank returns an error
```yaml
core:
  clickthrough:
    maxSessionLength: 60s

models:
  similar:
    type: als
    interactions: [click]
    factors: 100
    iterations: 100

  trending:
    type: trending
    weights:
      - interaction: click
        decay: 0.8
        weight: 1.0
```

Metarank log
```bash
12:36:31.101 INFO  ai.metarank.main.Main$ - Metarank v0.6.0 is starting.
[1.361s][info][gc] GC(2) Pause Young (Concurrent Start) (Metadata GC Threshold) 35M->17M(128M) 4.874ms
[1.361s][info][gc] GC(3) Concurrent Mark Cycle
[1.375s][info][gc] GC(3) Pause Remark 18M->18M(67M) 2.227ms
[1.386s][info][gc] GC(3) Pause Cleanup 18M->18M(67M) 0.008ms
[1.387s][info][gc] GC(3) Concurrent Mark Cycle 26.255ms
DecodingFailure(Missing required field, List(DownField(features)))
```
