### ISSUE TITLE
Can't start Metarank recommendations without personalization config

### ISSUE THREAD

**Issue by vgoloviznin** [metarank/metarank#958]
Given the following YAML config

```yaml
core:
  clickthrough:
    maxSessionLength: 60s

models:
  similar:
    type: als
    interactions: [click]
    factors: 100
    iterations: 100

  trending:
    type: trending
    weights:
      - interaction: click
        decay: 0.8
        weight: 1.0

features:
  - name: popularity
    type: number
    scope: item
    source: metadata.popularity
```

Gives an error after starting the event import
```bash
12:40:19.963 INFO  ai.metarank.flow.PrintProgress$ - imported 2048 events, perf=800.0rps
java.lang.Exception: empty feature set
	at ai.metarank.model.ItemValue$.fromState(ItemValue.scala:54)
	at ai.metarank.flow.ClickthroughJoinBuffer.$anonfun$handleRanking$1(ClickthroughJoinBuffer.scala:47)
	at map @ ai.metarank.flow.ClickthroughJoinBuffer.$anonfun$handleRanking$1(ClickthroughJoinBuffer.scala:47)
	at flatMap @ ai.metarank.flow.ClickthroughJoinBuffer.$anonfun$handleRanking$1(ClickthroughJoinBuffer.scala:47)
	at apply @ ai.metarank.fstore.memory.MemKVStore.get(MemKVStore.scala:9)
	at map @ ai.metarank.fstore.FeatureValueLoader$.$anonfun$fromStateBackend$7(FeatureValueLoader.scala:19)
	at apply @ ai.metarank.fstore.FeatureValueLoader$.$anonfun$fromStateBackend$4(FeatureValueLoader.scala:18)
	at flatMap @ ai.metarank.fstore.FeatureValueLoader$.$anonfun$fromStateBackend$4(FeatureValueLoader.scala:18)
	at apply @ ai.metarank.fstore.memory.MemKVStore.get(MemKVStore.scala:9)
	at flatMap @ ai.metarank.fstore.FeatureValueLoader$.$anonfun$fromStateBackend$3(FeatureValueLoader.scala:17)
	at apply @ ai.metarank.fstore.FeatureValueLoader$.fromStateBackend(FeatureValueLoader.scala:16)
	at flatMap @ ai.metarank.fstore.FeatureValueLoader$.fromStateBackend(FeatureValueLoader.scala:16)
	at flatMap @ ai.metarank.flow.ClickthroughJoinBuffer.handleRanking(ClickthroughJoinBuffer.scala:46)
	at apply @ ai.metarank.flow.ClickthroughJoinBuffer.process(ClickthroughJoinBuffer.scala:37)
	at map @ ai.metarank.flow.MetarankFlow$.$anonfun$process$11(MetarankFlow.scala:35)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
```
